WIP: gh-124 Add Dialog Component To Examples
zorko-io/zorko-platform pull request #150
Opened 2021-01-04 15:07 UTC by whiteadam2

- create ConfirmDialog
- put ConfirmDialog on ExamplePage

2021-01-04 17:15 UTC, yzhbankov commented on apps/web-portal-client/lib/components/dialog/Dialog.jsx
> +    return <></>
return null

2021-01-04 17:21 UTC, yzhbankov commented on apps/web-portal-client/lib/components/dialog/Dialog.jsx
> +          <IconButton onClick={() => onClose()}>
why we need this "x" button?
you can add a closing dialog by clicking outside the dialog and make this optional (on/off by props passing)

2021-01-04 17:22 UTC, yzhbankov commented
looks good

2021-01-05 08:48 UTC, nesterone requested changes

2021-01-05 08:48 UTC, nesterone commented on apps/web-portal-client/lib/components/dialog/ExitIcon.jsx
> +export function ExitIcon() {
Could we reuse the already existing <Image> component for that ?

2021-01-05 08:48 UTC, nesterone commented on apps/web-portal-client/lib/components/dialog/IconButton.jsx
> +export function IconButton({onClick, children, className}) {
> Could we reuse the already existing  component for that ?

same here

2021-01-13 16:21 UTC, nesterone requested changes

2021-01-13 16:21 UTC, nesterone commented on apps/web-portal-client/lib/components/Button.jsx
>    handleClick: PropTypes.func,
handleClick -> onClick

2021-01-13 16:21 UTC, nesterone commented on apps/web-portal-client/lib/components/dialog/ConfirmDialog.jsx
> +  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]),
it makes sense to extract that expression `PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node])` to separate file like `lib/utils/childrenPropTypes.js` and use it in all components where need to define `children` Props

2021-01-13 16:21 UTC, nesterone commented on apps/web-portal-client/lib/components/dialog/Dialog.jsx
> +  children: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.node), PropTypes.node]),
see comment regarding extraction of the prop type definition

2021-01-13 20:42 UTC, yzhbankov commented on apps/web-portal-client/lib/components/Button.jsx
> +  const {label, onClick, children, addClasses} = props
"addClasses" sounds like a verb but it is not. plz use something like "cssClass" or "className"

2021-01-13 20:43 UTC, yzhbankov commented on apps/web-portal-client/lib/components/dialog/ConfirmDialog.jsx
> +  if (!open) return <></>
return just null

2021-01-16 09:39 UTC, nesterone commented on apps/web-portal-client/lib/components/dialog/ConfirmDialog.jsx
> +            cssClass="bg-smooth-green hover:bg-smooth-green-light flex-auto"
It's not the best practice to pass `custom` css to such a component like `Button`

We have to standardize button types like, for example:  `<Button type="primary" label="Yes"  />`. We can start with two types of` primary`/`default`, then component would choose to which color to provide for primary and default


Another good practice for dialogs is to highlight the acton button (in confirm dialog it's `Yes`) with primary type and `Cancel` as default type

2021-01-16 09:39 UTC, nesterone commented on apps/web-portal-client/lib/components/dialog/ConfirmDialog.jsx
> +            cssClass="bg-smooth-green hover:bg-smooth-green-light flex-auto"
extracting to separate issue

2021-01-16 09:41 UTC, nesterone approved these changes

2021-01-16 09:41 UTC, merged