WIP: gh-125 Add Popover Component to Examples page
zorko-io/zorko-platform pull request #153
Opened 2021-01-15 22:07 UTC by whiteadam2

- install popper.js
- create example popover component

2021-01-20 17:23 UTC, nesterone requested changes

2021-01-20 17:23 UTC, nesterone commented on apps/web-portal-client/lib/features/examples/components/TippyExample.jsx
> +import 'tippy.js/dist/tippy.css'
I think in our case it makes sense to choose the Tippy library, it's much easier to use

However, we need to decide on where we would include `css` dependencies, I mean the one place to do that.

2021-01-22 19:55 UTC, whiteadam2 commented
close #125

2021-01-23 10:45 UTC, nesterone requested changes
It looks good !

2021-01-23 10:45 UTC, nesterone commented on apps/web-portal-client/lib/components/Popover.jsx
> +      duration={0}
Another way to write it is  to use spread for props 
<Tippy {...props} content={content} />
```
Popover.propTypes = {
  ...Tippy.propTypes,
  children: childrenPropTypes,
}

```

but we can leave as it is right now, let's just define  `duration` and `delay` in propTypes and defaultProps

2021-01-24 08:25 UTC, nesterone approved these changes

2021-01-24 08:25 UTC, merged