WIP: gh-118 toError cover with unit-tests
zorko-io/zorko-platform pull request #176
Opened 2021-01-23 08:55 UTC by whiteadam2

- extract toError func
- Make basic happy path tests

2021-01-24 08:26 UTC, nesterone requested changes

2021-01-24 08:26 UTC, nesterone commented on packages/util-use-case/lib/adapters/toError.test.mjs
> +  // t.assert(deps.log instanceof MockLogger, 'Deps should have prop log whitch istanceof MockLogger')
add here  checks that log.fatal was not called

2021-01-24 08:26 UTC, nesterone commented on packages/util-use-case/lib/adapters/toError.mjs
> +
Add [jsdocs](https://jsdoc.app/) notation, as an example refer to `makeRunner`

2021-01-25 08:23 UTC, whiteadam2 commented on packages/util-use-case/lib/adapters/toError.mjs
> +
Do you mean smth like that?
/**
 * Passes result to response as json,
 * @param {Error}error - error to convert
 * @param {Express.Request} req - request
 * @param {Express.Response} res - response
 * @param {Object} [deps] - dependencies
 * @param {CoreLogger} [deps.log] - logger instance
 * @return {*} - converted result, the same what we send over response
 */

2021-01-26 11:15 UTC, nesterone commented on packages/util-use-case/lib/adapters/toError.mjs
> +
yep
```
/**

Convert error to JSON and pass to response
@param {Error}error - error to convert
@param {Express.Request} req - request
@param {Express.Response} res - response
@param {Object} [deps] - dependencies
@param {CoreLogger} [deps.log] - logger instance
@return {*} - converted result, the same what we send over response
*/


```

2021-01-27 16:46 UTC, nesterone approved these changes

2021-01-27 16:46 UTC, merged