gh-207. Integrate dotenv with webpack
zorko-io/zorko-platform pull request #221
Opened 2021-02-21 16:31 UTC by yzhbankov

close #207

2021-02-22 06:41 UTC, nesterone commented
could you commit .env.sample file with an example of env vars ?

2021-02-22 19:03 UTC, nesterone requested changes

2021-02-22 19:03 UTC, nesterone commented on apps/web-portal-client/.env.sample
> +API_BASE_URL=http://localhost:7777
ZORKO_API_BASE_URL

2021-02-25 07:30 UTC, yzhbankov commented on apps/web-portal-client/.env.sample
> +API_BASE_URL=http://localhost:7777
done

2021-02-25 07:56 UTC, nesterone approved these changes, later dismissed

2021-02-25 08:13 UTC, nesterone approved these changes

2021-02-25 08:13 UTC, merged