WIP: gh-208. Add basic interface for an access-blob-storage package
zorko-io/zorko-platform pull request #281
Opened 2021-03-29 19:59 UTC by yzhbankov

2021-03-30 10:07 UTC, nesterone commented
Regarding interface:
- blob storage should be generic for any blob content, in other words it's should not include any entities like Preview or CSV files 
- under 'generic' we mean that customers of it's API can write and read blobs, navigate over buckets/folders , generate links with auth access 

```js
class BlobStorage

    writeBlob(options, readableStream) {}
   
    makeFolder(options) {}
    
   / **
     * @returns {ReadableStream} 
    **/
    readBlob(options) {} 

    generateLink(options) {}
    
    list(folder, options)

    remove(options)

```


Interface is raw and for discussible, just to show an idea

2021-03-30 10:11 UTC, nesterone requested changes

2021-03-30 10:11 UTC, nesterone commented on packages/access-blob-storage/lib/minio/MinioPreviewStorage.mjs
> +    return await this.#storage.putObject(this.#bucket, params.name, params.data)
We should put some effort in 'wrapping' underling api of minio

for example 'just' returning original response from minio is not enought we should return our format of response, it
even became more interesting that we also need to take care for `errors`, so each call for underlined api should try to handle not only happy path but failure too

2021-05-11 19:44 UTC, yzhbankov commented
@nesterone did you know a good example of a blob storage API? It is not clear to me what kind of interface should we implement and the use cases. Is the azure API(https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-rest-api, https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage, https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#blob-storage-resources) could be an example?

2021-05-18 05:39 UTC, nesterone commented
interface is ok, we need integration tests here to prof that module can work with minio

2021-05-21 15:02 UTC, nesterone requested changes

2021-05-21 15:02 UTC, nesterone commented on packages/access-blob-storage/lib/minio/MinioStorage.mjs
> +    this.#storage = new Minio.Client({
Configs should be taken from `.env`

2021-06-03 06:34 UTC, nesterone approved these changes

2021-06-03 06:34 UTC, merged